run:
  deadline: 3m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - generated
  skip-files:
    - ".*\\/test_common\\.go$"

output:
  format: colored-line-number # colored-line-number|line-number|json|tab|checkstyle
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - govet
    # - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    # default disabled
    - gosec
    - unconvert
    - goconst
    - goimports
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: false
    check-blank: false
  unused:
    check-exported: false
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
